### ISSUE TITLE
`validate_copyright` sometimes fails to parse new files

### ISSUE THREAD

**Issue by Alchez** [agritheory/test_utils#81]
```
validate_copyright.......................................................Failed
- hook id: validate_copyright
- exit code: 1

Traceback (most recent call last):
  File "/home/rohan/.cache/pre-commit/reposhwait_a/py_env-python3.12/bin/validate_copyright", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/rohan/.cache/pre-commit/reposhwait_a/py_env-python3.12/lib/python3.12/site-packages/test_utils/pre_commit/validate_copyright.py", line 62, in main
    validate_copyright(app, files)
  File "/home/rohan/.cache/pre-commit/reposhwait_a/py_env-python3.12/lib/python3.12/site-packages/test_utils/pre_commit/validate_copyright.py", line 32, in validate_copyright
    validate_and_write_file(file, initial_py_string, copyright_py_string)
  File "/home/rohan/.cache/pre-commit/reposhwait_a/py_env-python3.12/lib/python3.12/site-packages/test_utils/pre_commit/validate_copyright.py", line 50, in validate_and_write_file
    os.replace(temp_file_path, file)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp1hndyez_' -> 'beam/beam/overrides/inventory_dimension.py'
```

**Comment by agritheory** [comment]
@Alchez Has this recurred? I suspect it's related to your editor having a lock on the file. It's never happened to me.

**Comment by adamgranted** [comment]
@agritheory `shutil.move(temp_file_path, file)` works as a direct replacement for `os.replace(temp_file_path, file)` to fix the "Invalid cross-device link" error seen here and #111.

I opened a PR with this approach but it may be an oversimplification - #120 

It should also place nice with the changes #119 providing `os.replace` is.. well replaced.
